export const TAG_VOCABULARY: string[] = [
  // --- Project type / deliverable ---
  "logo design",
  "brand identity",
  "visual identity system",
  "brand guidelines",
  "style guide",
  "typeface design",
  "custom lettering",
  "wordmark",
  "logotype",
  "monogram",
  "icon set",
  "iconography",
  "app icon",
  "favicon",
  "business card",
  "letterhead",
  "stationery design",
  "packaging design",
  "label design",
  "poster design",
  "flyer",
  "brochure",
  "editorial layout",
  "magazine spread",
  "book cover",
  "album cover",
  "merchandise design",
  "signage",
  "environmental graphics",
  "wayfinding",
  "vehicle wrap",
  "billboard",
  "social media graphics",
  "social media template",
  "email template",
  "banner ad",
  "web design",
  "website mockup",
  "landing page",
  "mobile app UI",
  "app screen",
  "dashboard UI",
  "UI kit",
  "design system",
  "component library",
  "wireframe",
  "prototype",
  "presentation deck",
  "pitch deck template",
  "infographic",
  "data visualization",
  "chart design",
  "motion graphics",
  "animated logo",
  "GIF animation",
  "video title card",
  "lower third",
  "NFT collection art",

  // --- Typography ---
  "typography",
  "type specimen",
  "font pairing",
  "serif typeface",
  "sans-serif typeface",
  "slab serif",
  "display typeface",
  "script typeface",
  "monospace typeface",
  "variable font",
  "hand lettering",
  "calligraphy",
  "typographic poster",
  "kinetic typography",
  "grid-based typography",
  "type hierarchy",
  "letter spacing study",
  "custom glyphs",
  "numerals design",
  "typographic logo",

  // --- Visual identity elements ---
  "color palette",
  "brand color system",
  "gradient",
  "duotone",
  "monochrome design",
  "pattern design",
  "geometric pattern",
  "texture",
  "brand mascot",
  "brand mockup",
  "brand pattern system",
  "visual metaphor",
  "symbol mark",
  "abstract mark",
  "emblem",
  "badge design",
  "seal design",
  "crest design",

  // --- Layout & composition ---
  "grid system",
  "asymmetrical layout",
  "minimalist layout",
  "maximalist layout",
  "negative space composition",
  "modular layout",
  "responsive layout",
  "layout composition",
  "visual hierarchy",
  "whitespace usage",

  // --- Illustration & imagery ---
  "vector illustration",
  "flat illustration",
  "line art",
  "isometric illustration",
  "3D render",
  "3D typography",
  "photo composite",
  "collage design",
  "texture overlay",
  "halftone effect",
  "risograph style",
  "glitch effect",
  "gradient mesh",

  // --- Style / aesthetic descriptors ---
  "minimalist design",
  "maximalist design",
  "brutalist design",
  "retro design",
  "vintage design",
  "art deco style",
  "Bauhaus style",
  "Swiss design style",
  "corporate memphis style",
  "neo-brutalism",
  "y2k aesthetic",
  "grunge aesthetic",
  "luxury aesthetic",
  "playful design",
  "editorial style",
  "monospace aesthetic",
  "dark mode design",
  "light mode design",
  "high contrast design",
  "pastel palette",
  "neon aesthetic",
  "hand-drawn aesthetic",

  // --- Industry / context tags ---
  "tech branding",
  "fashion branding",
  "food and beverage branding",
  "startup branding",
  "nonprofit branding",
  "event branding",
  "music branding",
  "sports branding",
  "real estate branding",
  "wellness branding",
  "e-commerce design",
  "editorial publication",

  // --- Production / status metadata ---
  "final deliverable",
  "work in progress",
  "concept exploration",
  "design variation",
  "client presentation",
  "internal draft",
  "mockup render",
  "print-ready",
  "digital-only asset",
];
